import { IUsers } from "@/interfaces/users";

export const users: IUsers[] = [
    {
        id: "1a2b3c4d",
        firstName: "John",
        lastName: "Doe",
        otherNames: "Michael",
        email: "john.doe@example.com",
        userRole: "Admin",
        userType: "Partner",
        status: "active",
        createdat: "2023-08-01T08:30:00Z",
        updatedat: "2024-08-01T09:00:00Z",
    },
    {
        id: "2b3c4d5e",
        firstName: "Jane",
        lastName: "Smith",
        otherNames: "A.",
        email: "jane.smith@example.com",
        userRole: "Editor",
        userType: "Reporter",
        status: "inactive",
        createdat: "2023-07-15T10:00:00Z",
        updatedat: "2024-08-15T10:30:00Z",
    },
    {
        id: "3c4d5e6f",
        firstName: "Alice",
        lastName: "Johnson",
        otherNames: "Marie",
        email: "alice.johnson@example.com",
        userRole: "Contributor",
        userType: "Partner",
        status: "active",
        createdat: "2023-06-20T12:45:00Z",
        updatedat: "2024-08-20T13:00:00Z",
    },
    {
        id: "4d5e6f7g",
        firstName: "Bob",
        lastName: "Brown",
        otherNames: "Edward",
        email: "bob.brown@example.com",
        userRole: "Viewer",
        userType: "Reporter",
        status: "active",
        createdat: "2023-05-10T14:15:00Z",
        updatedat: "2024-08-10T14:45:00Z",
    },
    {
        id: "5e6f7g8h",
        firstName: "Charlie",
        lastName: "Davis",
        otherNames: "James",
        email: "charlie.davis@example.com",
        userRole: "Admin",
        userType: "Partner",
        status: "inactive",
        createdat: "2023-04-01T16:30:00Z",
        updatedat: "2024-08-01T17:00:00Z",
    },
    {
        id: "6f7g8h9i",
        firstName: "Diana",
        lastName: "Evans",
        otherNames: "Grace",
        email: "diana.evans@example.com",
        userRole: "Editor",
        userType: "Reporter",
        status: "active",
        createdat: "2023-03-25T18:00:00Z",
        updatedat: "2024-08-25T18:30:00Z",
    },
    {
        id: "7g8h9i0j",
        firstName: "Edward",
        lastName: "Franklin",
        otherNames: "George",
        email: "edward.franklin@example.com",
        userRole: "Contributor",
        userType: "Partner",
        status: "inactive",
        createdat: "2023-02-15T20:15:00Z",
        updatedat: "2024-08-15T20:45:00Z",
    },
    {
        id: "8h9i0j1k",
        firstName: "Fiona",
        lastName: "Garcia",
        otherNames: "Helen",
        email: "fiona.garcia@example.com",
        userRole: "Viewer",
        userType: "Reporter",
        status: "active",
        createdat: "2023-01-10T22:00:00Z",
        updatedat: "2024-08-10T22:30:00Z",
    },
];


